# Generated by Django 3.2.9 on 2022-09-30 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
